# Generated by Django 3.1.4 on 2020-12-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioacc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
